CREATE DATABASE premier_rides;
USE premier_rides;
CREATE TABLE admins(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),password VARCHAR(255));
CREATE TABLE vehicles(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),price DECIMAL(10,2),image VARCHAR(255));
CREATE TABLE bookings(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),phone VARCHAR(30),pickup VARCHAR(255),destination VARCHAR(255),status VARCHAR(30),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO admins(username,password) VALUES('admin','admin123');